name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting: 
    runs-on: [ubuntu-latest,windows-latest,macOS-latest]
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        greeting: "Hey **#** from Watermrk repo"
        issue-message: "This is your first issue.  "
        pr-message: "Message that will be displayed on users' first pull request"
